---
title: 'Otus R Analytics: Home task 1.1: Motivational Essay'
author: "Andrej Pawluczenko"
date: "05.08.2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Здесь я кратко изложу:

<ol type="a">
  <li>какие технические ограничения в текущей деятельности я хотел бы приодолеть при помощи R;</li>
  <li>какие перспективы вижу в использовании R для развития своей деятельности.</li>
</ol>

Эти пункты я опишу в рамках двух своих основных направлений деятельности.

## I. Работа

### Технические ограничения

В данный момент наша работа (подготовка мониторингов СМИ и социальных медиа по ключевым словам заказчика) на финальном этапе отнимает много времени из-за расчетов, которые традиционно выполняются в Excel (и оформляются в PowerPoint). С помощью R я мог бы автоматизировать большую часть обработки данных и расчетов.

### Перспективы

В перспективе мы могли бы наряду с автоматизацией рутины разработать и предложить клиентам новые эксклюзивные инструменты измерения инфополя, например, автоматизировать оценку тональности (сейчас доступные нам автоматические инструменты оставляют желать лучшего), вычислять информационные атаки, предсказывать резонанс и медийные последствия высказываний и событий, рассчитывать семантический дифференциал для оценки «имиджа» бренда заказчика, создать панель индикаторов в реальном времени и др.

А вообще мне интересно анализировать любые «гуманитарные» данные: кроме сообщений и отзывов, например, поведение клиентов, оценка персонала и другие HR-метрики. А на предыдущей работе у нас получилось повысить успешность редакционной email-рассылки за счет анализа компонентов, способствующих читательскому интересу :)

## II. Наука

Так получилось, что я окончил аспирантуру по культурологии, но не закончил диссертацию. Тема звучит страшно: «Культурная парадигма южнославянского Национального возрождения в XVIII веке». Не закончил потому, что несмотря на хорошее понимание проблемы не видел возможности создать работу по всем строгим критериям научности, свободную от господствующего в наших социо-гуманитарных исследованиях субъективизма и релятивизма. Сейчас я уже представляю, как это сделать.

### Ограничения

Поскольку в моем проекте «культурная парадигма» получит практически математическое определение, нужен инструмент, позволяющий оценить качественные данные (других из балканских стран XVIII века нам и не осталось) количественно. Я знаю, что в R есть среда для интерпретативного контент-анализа (RQDA и не только). Результат контент-анализа тоже должны поддаваться подсчетам, позволяющим проверять гипотезы. Поэтому я хотел бы овладеть инструментами R для обработки неструктурированных текстов и статистического анализа прежде всего качественных данных. желательно при этом понимать стоящую за ними математику :)

### Перспективы

Я вижу большие перспективы социологических исследований с использованием контент-анализа (классический, не интерпретативный, контент-анализ сейчас хорошо автоматизируется и известен как Text Mining). Как написал один из преподавателей нашего курса, «Одна из проблем психометрии — искажение полученных данных ментальным представлением человека о себе. Этих искажений лишен анализ неструктурированных данных, который может давать доступ в процессы психики, неискаженные искусственными, наигранными проявлениями». То, чем я хотел бы (в идеале) заниматься находится как раз на стыке культурологии, классической социологии и когнитивных наук.

```{r echo=FALSE}
cat('Спасибо за внимание!\n')
```