---
title: "Markdown practice"
author: "Лапуцкая Оксана"
date: '5 августа 2019 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

1. Выбираем датасет для анализа из пакета datasets. Смотрим, что он представляет собой (summary,str), строим основные графики (pie-chart,  bar chart, boxplot) c помощью plot или функций из пакета ggplot2, иллюстрирующие то, как распределены данные. 
2. Применяем форматирование текста, добавляем ссылку на описание данных из R Documentation
3. Вставляем изображение - фото социологов, собравших этот датасет, или любую другую картинку по теме
4. Гуглим исследование по названию из References и смотрим формулы, которые использовали авторы. Вставляем их в документ с помощью LaTeX
5. Выкладываем это задание и *все предыдущие домашние работы* на github


**Задание считается выполненным, когда: **

* Предоставлена ссылка на github repo с заданиями (1 балл)
* Построено 3 различных графика (1 балл)
* Использовано разное форматирование текста, вставлены ссылки и картинки (1 балл)
* Прописаны подробные комментарии по ходу выполнения  кода для удобства чтения и проверки (0.5 балла)
* Вставлена формула (1 балл)
* Задание принято с первого раза без доработок в установленные сроки (0,5 балла).

###Минимальное количество баллов для зачета - 4

