---
title: "hw_3_1"
author: "Бикмаев Руслан"
date: "08 10 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## ДЗ 2.1 data.table - ключи и модификация по ссылке

1. Для упражнения используются данные морфологического словаря, скаченного на одном из прошлых занятий.   
[ссылка.zip](http://opencorpora.org/files/export/dict/dict.opcorpora.txt.zip)  
В случае, если данные не были сохранены, вновь скачайте данный файл (произвольным способом) 
Можно использовать изученные на занятии настройки fread(). Словарь должен быть очищен от пустых, индексных строк и разделен на два столбца, первый из которых содержит слово в кириллице, а второй только теги части речи (ADJF, NOUN и тд).
Можно попробовать настроить  арг. "sep" и "sep2" в функции fread и затем удалить ненужные столбцы, возможна замена разделителей, либо отрезание ненужной части функцией  gsub(), возможна нарезка скалярных значений на элементы с помощью strsplit() и выборка нужного элемента по индексу:w
.
Можно очистку данных выполнить сторонними утилитами (но, естественно, не вручную).
То есть выбор способа чистки данных произвольный. 

Пример:
          V1     V2
 1:       ЁЖ   NOUN     
 2:      ЕЖА   NOUN      
 3:      ЕЖУ   NOUN     
 4:      ЕЖА   NOUN          

Если не получится очистить данные (вторая колонка останется в виде "NOUN,inan,masc sing,accs"), можно провести последующие измерения на "полуочищенных" данных.


2. Создайте глубокую копию словаря и сохраните её во вторую переменную.

3. В первой переменной задайте ключи, а вторую проиндексируйте (первый столбец).
Измерьте c помощью microbenchmark() скорость поиска по произвольному слову (напр. "ЁЖИКОВ") в обоих вариантах (key, index)
Код и результаты измерений впишите в ДЗ.
Вопросы можно обсудить в чате.


Желательно сдать домашнее задание до 23:59 13.10.2019 г.

**Задание считается выполненным, когда:**
 * Домашняя работа сдана (1 балл)
 * Измерения проведены корректно, описание подробное (1 балл)
 * Код оформлен согласно рекомендациям tidyverse (1 балл)
 
**Дополнительные баллы:**
 * Произведена очистка данных (3 балла) 
 * Задание сдано до рекомендуемого дедлайна (1 балл)
 * Задание сдано с 1 попытки (1 балл)

**Минимальное количество баллов для зачета - 3**

