---
title: "ДЗ 6.2. Предиктивная аналитика и статистические выводы"
author: "Катин Алексей"
date: "12 03 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Если кинуть игральную кость шесть раз, какова вероятность что хоть раз выпадет 6? 

2. Тест Minnesota Paper Form Board (RMPFB) измеряет невербальные способности решения проблем, относящихся к пространственному мышлению. Тест RMPFB разработан таким образом, что результаты теста могут быть смоделированы с помощью нормального распределения со средним значением 43 балла и стандартным отклонением 8 баллов.
а) Какая доля всех тестируемых будет иметь балл RMPFB выше 50?
б) Какая доля всех прошедших тестирование будет иметь оценку RMPFB ниже 30 баллов?
в) Какая оценка теста для первого квантиля? (у 25% участников оценка ниже). Значение Z для 25% -0.675.

3. Следующий вопрос был задан более чем 50 000 учащимся в рамках стандартизированного статистического теста: «Верно или неверно: р-величина - это вероятность того, что нулевая гипотеза верна.» Для случайной выборки из 400 студентов, которые прошли тестирование, 175 ответили «истина», а 225 ответили «ложь». Гадают ли студенты на ответ или нет? Проведите соответствующий тест гипотезы, чтобы ответить на этот вопрос.

4. Большая бухгалтерская компания недавно отобрала 100 человек для участия в программе обучения управлению. Из них 76 мужчин и 24 женщины. Компания утверждает, что она выбрала 100 человек наугад из числа подходящих сотрудников, 800 женщин и 1200 мужчин. Соответствует ли выборка утверждению компании, или женщины составляют значительно меньшую долю отобранных для программы обучения, чем доля подходящих под условия программы женщин?

5. В группе из 62 мужчин, подвергшихся стрессовой ситуации, среднее число ударов сердца в минуту составило 126, а стандартное отклонение - 4.
а) Построить и интерпретировать 95% -ный доверительный интервал для матожидания сердечного ритма в минуту.
б) Проверить гипотезу о том, что среднее значение составляет 118 ударов в минуту, в сравнении с альтернативой, согласно которой матожидание сердечных сокращений превышает 118 ударов в минуту.

6. Две команды Вашингтон Капиталз и Детройт ред Уингз играют серию плейофф из семи игр. Вашингтон - команда получше, и с вероятностью 60% выигрывает в каждой игре. 
а) Какова вероятность того, что Детроит выиграют хотя бы одну игру?
б) Создайте симуляцию Монте-Карло, чтобы подтвердить свой ответ. Используйте 10000 симуляций. 
Используйте следующий код для генерации результатов первых четырех игр:
detroit_wins <- sample(c(0,1), 4, replace = TRUE, prob = c(0.6, 0.4))